/**
 * @file State constant / ES module
 * @module emoji.constant
 * @author Tandv <https://github.com/mchemistry>
 */

// emoji shothand comment
export const EMOJI_SHOTHAND = {
  smile: `smile`,
  cry: `cry`,
  smile_D: `smileD`,
  sad: `sad`,
  smile_P: `smileP`,
  shark: `shark`,
  dog: `dog`,
  puh: `puh`,
  ah: `ah`,
  haha: `haha`,
  dou_pistol: `dou_pistol`,
  atata: `atata`,
  draka: `draka`,
  pirate: `pirate`,
  punish: `punish`,
  aaa: `aaa`,
  blabla: `blabla`,
  bratok: `bratok`,
  like: 'like',
  fuu: `fuu`,
  gg: `gg`,
  gy: `gy`,
  gyy: `gyy`,
  ha: `ha`,
  help_me: `help_me`,
  hm: `hm`,
  hrap: `hrap`,
  krasn: `krasn`,
  lol: `lol`,
  plak: `plak`,
  preved: `preved`,
  rofl: `rofl`,
  shok: `shok`,
  sorry: `sorry`,
  stena: `stena`,
  vosadok: `vosadok`,
  yahoo: `yahoo`,
  zloj: `zloj`,
  romawki: `romawki`,
  raza2: `roza2`,
  alkawi: `alkawi`,
  arbuz: `arbuz`,
  drinks: `drinks`,
  jajca: `jajca`,
  obed: `obed`,
  apl: `apl`,
  clapping: `clapping`,
  nono: `nono`,
  ded_moroz: `ded_moroz`,
  ded_snegur2: `ded_snegur2`,
  chmok: `chmok`,
  loveman: `loveman`,
  kul2: `kul2`,
}

// gif image API end point
export const GIF_SOURCE_API = {
  smile: `https://data2.m4v.me/images/smileys/simply/).gif`,
  cry: `https://data2.m4v.me/images/smileys/user/emotions/cry.gif`,
  smile_D: `https://data2.m4v.me/images/smileys/simply/D.gif`,
  sad: `https://data2.m4v.me/images/smileys/simply/(.gif`,
  smile_P: `https://data2.m4v.me/images/smileys/simply/P.gif`,
  shark: `https://data2.m4v.me/images/smileys/user/animals/akula.gif`,
  dog: `https://data2.m4v.me/images/smileys/user/animals/sobaka.gif`,
  puh: `https://data2.m4v.me/images/smileys/user/animals/puh.gif`,
  ah: `https://data2.m4v.me/images/smileys/user/emotions/ah.gif`,
  haha: `https://data2.m4v.me/images/smileys/user/emotions/haha.gif`,
  dou_pistol: `https://data2.m4v.me/images/smileys/user/brawl_weapons/2pistoleta.gif`,
  atata: `https://data2.m4v.me/images/smileys/user/brawl_weapons/atata.gif`,
  draka: `https://data2.m4v.me/images/smileys/user/brawl_weapons/draka.gif`,
  pirate: `https://data2.m4v.me/images/smileys/user/brawl_weapons/pirat.gif`,
  punish: `https://data2.m4v.me/images/smileys/user/brawl_weapons/punish.gif`,
  aaa: `https://data2.m4v.me/images/smileys/user/emotions/aaa.gif`,
  blabla: `https://data2.m4v.me/images/smileys/user/emotions/blabla.gif`,
  bratok: `https://data2.m4v.me/images/smileys/user/emotions/bratok.gif`,
  like: 'https://data2.m4v.me/images/smileys/user/emotions/dovolen.gif',
  fuu: `https://data2.m4v.me/images/smileys/user/emotions/fuu.gif`,
  gg: `https://data2.m4v.me/images/smileys/user/emotions/gg.gif`,
  gy: `https://data2.m4v.me/images/smileys/user/emotions/gy.gif`,
  gyy: `https://data2.m4v.me/images/smileys/user/emotions/gyy.gif`,
  ha: `https://data2.m4v.me/images/smileys/user/emotions/ha.gif`,
  help_me: `https://data2.m4v.me/images/smileys/user/emotions/helpme.gif`,
  hm: `https://data2.m4v.me/images/smileys/user/emotions/hm.gif`,
  hrap: `https://data2.m4v.me/images/smileys/user/emotions/hrap.gif`,
  krasn: `https://data2.m4v.me/images/smileys/user/emotions/krasn.gif`,
  lol: `https://data2.m4v.me/images/smileys/user/emotions/lol.gif`,
  plak: `https://data2.m4v.me/images/smileys/user/emotions/plak.gif`,
  preved: `https://data2.m4v.me/images/smileys/user/emotions/preved.gif`,
  rofl: `https://data2.m4v.me/images/smileys/user/emotions/rofl.gif`,
  shok: `https://data2.m4v.me/images/smileys/user/emotions/shok.gif`,
  sorry: `https://data2.m4v.me/images/smileys/user/emotions/sorry.gif`,
  stena: `https://data2.m4v.me/images/smileys/user/emotions/stena.gif`,
  vosadok: `https://data2.m4v.me/images/smileys/user/emotions/vosadok.gif`,
  yahoo: `https://data2.m4v.me/images/smileys/user/emotions/yahoo.gif`,
  zloj: `https://data2.m4v.me/images/smileys/user/emotions/zloj.gif`,
  romawki: `https://data2.m4v.me/images/smileys/user/flowers/romawki.gif`,
  raza2: `https://data2.m4v.me/images/smileys/user/flowers/roza2.gif`,
  alkawi: `https://data2.m4v.me/images/smileys/user/food_alcohol/alkawi.gif`,
  arbuz: `https://data2.m4v.me/images/smileys/user/food_alcohol/arbuz.gif`,
  drinks: `https://data2.m4v.me/images/smileys/user/food_alcohol/drinks.gif`,
  jajca: `https://data2.m4v.me/images/smileys/user/food_alcohol/jajca.gif`,
  obed: `https://data2.m4v.me/images/smileys/user/food_alcohol/obed.gif`,
  apl: `https://data2.m4v.me/images/smileys/user/gestures/apl.gif`,
  clapping: `https://data2.m4v.me/images/smileys/user/gestures/clapping.gif`,
  nono: `https://data2.m4v.me/images/smileys/user/gestures/nono.gif`,
  ded_moroz: `https://data2.m4v.me/images/smileys/user/holidays/ded_moroz.gif`,
  ded_snegur2: `https://data2.m4v.me/images/smileys/user/holidays/ded_snegur2.gif`,
  chmok: `https://data2.m4v.me/images/smileys/user/love/chmok.gif`,
  loveman: `https://data2.m4v.me/images/smileys/user/love/loveman.gif`,
  kul2: `https://data2.m4v.me/images/smileys/user/gestures/kul2.gif`,
}
