export const getters = {
  tracks: ({ tracks }) => tracks,
  isPlay: ({ isPlay }) => isPlay,
  isShuffle: ({ isShuffle }) => isShuffle,
  repeat: ({ repeat }) => repeat,
  currentTime: ({ currentTime }) => currentTime,
  barTimer: ({ barTimer }) => barTimer,
  audio: ({ audio }) => audio,
  canPlay: ({ canPlay }) => canPlay,
  top: ({ top }) => top,
  saveIndexOfLyzik: ({ saveIndexOfLyzik }) => saveIndexOfLyzik,
  muted: ({ muted }) => muted,
  currentTrackIndex: ({ currentTrackIndex }) => currentTrackIndex,
  currentTrack: ({ currentTrack }) => currentTrack,
  imgFront: ({ imgFront }) => imgFront,
  imgBack: ({ imgBack }) => imgBack,
  state: ({ state }) => state,
}
