import data from '@/static/data/muzik.json'

export const state = () => ({
  tracks: data.tracks,
  originalTracks: data.tracks,
  isShuffle: false,
  repeat: 0,
  duration: null,
  time: 0,
  currentTime: null,
  barTimer: 0,
  isTimerPlaying: false,
  currentTrack: null,
  currentTrackIndex: 0,
  isPlay: false,
  canPlay: false,
  top: 0,
  saveIndexOfLyzik: 3,
  muted: false,
  lyzik: [
    '',
    'Rise',
    'Jonas Blue ft Jack & Jack',
    '...',
    "We're gonna ri-ri-ri-ri-rise 'til we fall",
    'This time we got no no no no future at all',
    "They wanna ke-ke-keep us down but they can't hold us down anymore",
    "We're gonna ri-ri-ri-ri-rise 'til we fall.",
    '...',
    'When we hit the bottom, then it goes up',
    'Climb to the top with you',
    "We're gonna be the breaks, once whoever waits",
    'Ya I could be talking to you',
    'They tryna hate hate hate',
    "But we won't change, change anything at all",
    "We're gonna ri-ri-ri-ri-rise 'til we fall.",
    '...',
    'They think we just dropped out',
    "Living at my mom's house",
    'Paris must be so proud',
    'They know it all',
    "They don't speak our language",
    "They say we're too savage",
    "No, no we don't need them anymore.",
    '...',
    "We'll ri-ri-ri-ri-rise 'til we fall",
    "We'll ri-ri-ri-ri-rise 'til we fall",
    "They don't speak our language",
    "They say we're too savage, ya",
    "No, no we don't need them anymore",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise 'til we fall.",
    '...',
    "So we're going no no no no no no nowhere",
    "But we they don't know know know is we don't don't care",
    "We're gonna keepin' on, keepin' on going til' we can't go no more.",
    'When we hit the bottom, then it goes up',
    'Climb to the top with you',
    "We're gonna be the breaks, once whoever waits",
    'Ya I could be talking to you',
    'They tryna hate hate hate',
    "But we won't change, change anything at all",
    "We're gonna ri-ri-ri-ri-rise 'til we fall.",
    '...',
    'They think we just dropped out',
    "Living at my mom's house",
    'Paris must be so proud',
    'They know it all',
    "They don't speak our language",
    "They say we're too savage",
    "No, no we don't need them anymore.",
    '...',
    "We'll ri-ri-ri-ri-rise 'til we fall",
    "We'll ri-ri-ri-ri-rise 'til we fall",
    "They don't speak our language",
    "They say we're too savage, ya",
    "No, no we don't need them anymore",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise",
    "We're gonna ri-ri-ri-ri-rise 'til we fall.",
  ],
  timerLyzik: [
    0,
    0,
    0,
    2,
    3,
    4,
    8,
    13,
    18,
    21,
    22,
    24,
    26,
    29,
    31,
    33,
    36,
    39,
    40,
    42,
    44,
    46,
    48,
    51,
    53,
    57,
    58,
    62,
    66,
    69,
    71,
    77,
    81,
    86,
    90,
    93,
    94,
    99,
    103,
    112,
    115,
    117,
    119,
    122,
    123,
    126,
    129,
    130,
    132,
    135,
    137,
    139,
    141,
    144,
    148,
    149,
    153,
    157,
    159,
    162,
    167,
    172,
    176,
    181,
  ],
})
